adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
This commit will update to use new Vungle SDK init API.
IOS-2890
=> Updated SDK init api

adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
This commit will add fix for sequential download stuck.
IOS-2980
=> [IOS-2980]Fix for sequential download stuck issue

adapters/Vungle/VungleAdapter/GADMAdapterVungleInterstitial.m, adapters/Vungle/VungleAdapter/GADMAdapterVungleRewardedAd.m, adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m, adapters/Vungle/VungleAdapter/GADMAdapterVungleUtils.h, adapters/Vungle/VungleAdapter/GADMAdapterVungleUtils.m, adapters/Vungle/VungleAdapter/VungleRouterConfiguration.m
AdMob made many changes in Vungle Adapter in their official repo, especially for `GADMAdapterVungleRouter.m` file:
https://github.com/googleads/googleads-mobile-ios-mediation/blob/master/adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
We should merge all these changes to our 6.7.0 AdMob Adapter.
IOS-3051
=> [IOS-3051]Add latest changes from AdMob

adapters/Vungle/VungleAdapter/GADMAdapterVungleConstants.h
Updating adapter version.
IOS-4005
=> [IOS-4005] Updating adapter version.

adapters/Vungle/VungleAdapter/GADMAdapterVungleConstants.h
[IOS-4074] Updating adapter version
IOS-4074
[IOS-4074]: https://vungle.atlassian.net/browse/IOS-4074
=> [IOS-4074] Updating adapter version

adapters/Vungle/CHANGELOG.md, adapters/Vungle/VungleAdapter/GADMAdapterVungleConstants.h
Updating adapter version and changelog.
IOS-4230
=> [IOS-4230] Updating adapter version and changelog.

adapters/Vungle/VungleAdapter/GADMAdapterVungleConstants.h
Updating adapter version.
IOS-4433
=> [IOS-4433] Updating adapter version.

adapters/Vungle/VungleAdapter/GADMAdapterVungleConstants.h
=> [IOS-4481] Updating version

adapters/Vungle/VungleAdapter/GADMAdapterVungleConstants.h
Updating adapter version.
IOS-4568
=> [IOS-4568] Updating adapter version.

adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleBanner.m, adapters/Vungle/VungleAdapter/GADMAdapterVungleBanner.m
Removing the willPresentFullScreen callbacks.
IOS-4627
=> [IOS-4627] Removing the willPresentFullScreen callbacks.

adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleNativeAd.m
This includes changes to support HB and Realtime Native ads. Includes calling new native ads API.
IOS-4933
=> RTB Native ads development support

adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleNativeAd.h, adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleNativeAd.m, adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.h, adapters/Vungle/VungleAdapter/GADMediationAdapterVungle.m
This commit addresses Google's PR feedback for the native ad/COPPA PR
=> This commit will address Google PR feedback for the native ads PR.

adapters/Vungle/VungleAdapter/GADMediationAdapterVungle.m
This commit includes loadRewardedInterstitialAdForAdConfiguration
in GADMediationAdapterVungle class
IOS-5101
=> Update Adapter code for RewardedInterstitial.

adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleNativeAd.m
This commit will add implementation for the optional methods for native ad as requested by Google.
IOS-5209
=> [IOS-5209] This commit will add implementation for the optional methods for native ad

adapters/Vungle/VungleAdapter.xcodeproj/project.pbxproj, adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleInterstitial.m, adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleNativeAd.m, adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleRewardedAd.m, adapters/Vungle/VungleAdapter/GADMAdapterVungleBanner.m, adapters/Vungle/VungleAdapter/GADMAdapterVungleInterstitial.m, adapters/Vungle/VungleAdapter/GADMAdapterVungleRewardBasedVideoAd.m, adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m, adapters/Vungle/VungleAdapter/GADMAdapterVungleUtils.h, adapters/Vungle/VungleAdapter/GADMediationAdapterVungle.m, adapters/Vungle/VungleAdapter/VungleRouterConsent.m
Updating the framework name for the adapter files.
IOS-5287
=> [IOS-5287] Updating the framework name for the adapter files.

adapters/Vungle/VungleAdapter/GADMAdapterVungleUtils.h, adapters/Vungle/VungleAdapter/VungleRouterConsent.m
This commit updates the SDK name change.
IOS-5350
=> [IOS-5350] This commit updates the SDK name change.

adapters/Vungle/VungleAdapter.xcodeproj/project.pbxproj, adapters/Vungle/VungleAdapter/Bidding/GADMAdapterVungleBiddingRouter.m, adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleBanner.h, adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleBanner.m, adapters/Vungle/VungleAdapter/GADMAdapterVungleConstants.h, adapters/Vungle/VungleAdapter/GADMediationAdapterVungle.m
This commit re-adds the bidding banner class.
IOS-5508
=> [IOS-5508] This commit re-adds the bidding banner class.

adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleBanner.h, adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleBanner.m, adapters/Vungle/VungleAdapter/GADMAdapterVungleBanner.m, adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.h, adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m, adapters/Vungle/VungleAdapter/GADMAdapterVungleUtils.h, adapters/Vungle/VungleAdapter/GADMAdapterVungleUtils.m, adapters/Vungle/VungleAdapter/GADMediationAdapterVungle.m
Code review feedback.
IOS-5659
=> [IOS-5659] Code review feedback.

adapters/Vungle/VungleAdapter.xcodeproj/project.pbxproj, adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleBanner.h, adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleBanner.m, adapters/Vungle/VungleAdapter/GADMAdapterVungleBanner.m, adapters/Vungle/VungleAdapter/GADMediationAdapterVungle.m
This commit adds the banner bidding class.
IOS-5508
=> [IOS-5508] This commit adds the banner bidding class.

adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleBanner.m, adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleInterstitial.m, adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleNativeAd.m, adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleRewardedAd.m
This commit ads the watermark implementation for the ad formats.
IOS-5753
=> [IOS-5753] This commit ads the watermark implementation for the ad formats.

adapters/LiftoffMonetize/LiftoffMonetizeAdapter/Bidding/GADMediationVungleBanner.m, adapters/LiftoffMonetize/LiftoffMonetizeAdapter/GADMAdapterVungleBanner.m, adapters/LiftoffMonetize/LiftoffMonetizeAdapter/GADMAdapterVungleConstants.h, adapters/LiftoffMonetize/LiftoffMonetizeAdapter/GADMAdapterVungleUtils.h, adapters/LiftoffMonetize/LiftoffMonetizeAdapter/GADMAdapterVungleUtils.m
This commit will update the adMob to use VungleBannerView instead of VungleBanner. Also adds support for in-feed apis.
IOS-6793
=> In-feed ads support for adMob.

adapters/LiftoffMonetize/LiftoffMonetizeAdapter/Bidding/GADMediationVungleNativeAd.m
This commit will add Native ads aspectRatio support for adapter.
IOS-7016
=> Native ads Aspect Ratio Support.
