- adapters/Vungle/VungleAdapter/GADMAdapterVungleInterstitial.m
- adapters/Vungle/VungleAdapter/VungleRouter.m
To fix the issue which MREC ad doesn't close when we  tap “Close” button on TestBannerAdViewController.
The root cause is when we create a new MREC ad view : self.isMrecPlaying of VungleRouter class is set to YES, then the old MREC ad view will be cleaned up, which will call completeBannerAdViewForPlacementID: method of  VungleRouter class. In completeBannerAdViewForPlacementID: method, the self.isMrecPlaying  is set to No, which could lead to when we close TestBannerAdViewController, cannot call [[VungleSDK sharedSDK] finishedDisplayingAd].
IOS-2491
> [IOS-2491]Fix do not close MREC issue

- adapters/Vungle/Public/Headers/VungleAdNetworkExtras.h
- adapters/Vungle/VungleAdapter/VungleRouter.m
AdMob iOS adapter 6.5.0 does not have option to add video orientation when configuring VungleAdNetworkExtras. We should include this setting to have parity with Android.
https://github.com/Vungle/googleads-mobile-ios-mediation/blob/6.5.x/adapters/Vungle/VungleAdapter/VungleRouter.m#L233-L238
IOS-2582
> [IOS-2582]AdMob Adapter - Add video orientation to play ad option

- adapters/Vungle/VungleAdapter/GADMAdapterVungleInterstitial.m
One tricky aspect is that not all our banner ad sizes (320x50, 300x50, 728x90) confirm to the AdMob constant banner sizes. AdMob does not have a 300x50 in its set constants.  For 300x50, we may to have convert the way Facebook has done. 
We could reference what Facebook does in their AdMob adapter code to take care of supported banner sizes:
https://github.com/googleads/googleads-mobile-ios-mediation/blob/master/adapters/Facebook/FacebookAdapter/GADFBBannerAd.m#L35
IOS-2684
> [IOS-2684]Support short banner size

- adapters/Vungle/VungleAdapter/GADMAdapterVungleConstants.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleInterstitial.m
The current Admob-iOS implementation rejects ads if the banners do not conform to Vungle supported sizes. Instead of rejecting them, we should get the closest matching size and return the appropriate Vungle ad size.
References:
https://github.com/googleads/googleads-mobile-ios-mediation/blob/master/adapters/Facebook/FacebookAdapter/GADFBBannerAd.m#L39
https://developers.google.com/admob/ios/banner/adaptive
https://developers.google.com/admob/ios/banner/smart
IOS-2765
> [IOS-2765]Support smart and adaptive banners in Admob adapters

- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
As Aki mentioned in ticket [IOS-2811](https://vungle.atlassian.net/browse/IOS-2811):
[GADMAdapterVungleRouter.m#L350 ](https://github.com/Vungle/googleads-mobile-ios-mediation/blob/6.5.2/adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m#L350)
`I found that in this flow (after refresh to 2nd ad and close it), _isBannerPresenting is NO or (delegate.bannerState == BannerRouterDelegateStatePlaying) is not true, so then, [[VungleSDK sharedSDK] finishedDisplayingAd]; won’t be called.  So report_ad won’t be fired.
Even more, banner ad is not closed properly. `
After the investigation, this issue is caused by SDK calling the method `- (void)vungleDidCloseAdWithViewInfo:placementID:` for the previous Banner ad firstly when closed the previous Banner ad, in this method the …
> [IOS-2811]Fix report ad is not called issue

- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
During the test of AdMob Adapter, I found  the callbacks `-(void)willCloseAd:didDownload:` and   `-(void)didCloseAd:didDownload:` of Interstitial Ad cannot be called, this PR is the fix of this issue.
> Fix Interstitial Ad callback issue

- adapters/Vungle/Public/Headers/VungleAdNetworkExtras.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleDelegate.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleInterstitial.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
- adapters/Vungle/VungleAdapter/VungleAdNetworkExtras.m
https://vungle.atlassian.net/browse/IOS-2827
AdMob supports multiple Banners with same placementID, which Vungle doesn't support.
This change handles that limitation at adapter level, as AdMob allows multiple requests for same placement to be created simultaneously.
“UUID” needs to be added in VungleAdNetworkExtras class to be able to differentiate the adRequest for “refresh” case from one for secondary banner, with the same UnitID (= Placement ID).
AdMob told us VungleAdNetworkExtras should hold the same “values” (instance might be re-created) for refresh case, we can use this behavior to fix this issue.
IOS-2827
> [IOS-2827]Support multiple Banners with same placementID

- adapters/Vungle/Public/Headers/VungleAdNetworkExtras.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleDelegate.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleInterstitial.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
This PR includes below three improvements:
1) When play multiple Banners with different placementIds, we need to add some judgments and protections to make sure only one Vungle Banner is displaying at the same time in multi threads environment.
2) AdMob SDK always releases the Banner delegate early, which could lead to some callbacks of  Banner cannot be received. So I update the logic to manage Banner delegate lifecycle, after calling the delegate method `vungleDidCloseAdWithViewInfo:placementID:`, then adapter could release the Banner delegate.
3) On Android side, the AdMob Adapter allowed the users to set UUID of `NetworkExtras` class. On iOS side, the UUID is `readonly` and cannot be set by users. The value of UUID is created and assigned to random value in the `init` method. We …
> [IOS-2839][IOS-2838]Multiple Banners with same placementId improvement

- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
When I investigated the issue in ticket IOS-2833(https://vungle.atlassian.net/browse/IOS-2833), I found that in `-(void)vungleAdPlayabilityUpdate:placementID:error:` callback method, if the parameter `error` is nil and `isAdPlayable` is NO passed to this method, this will not call `[delegate adNotAvailable:error];` method to notify the Interstitial delegate the ad is not filled. This could lead to the AdMob SDK calls the Interstitial delegate’s clean up method until time out, which will take longer time.  Then AdMob SDK could request next priority placementID ad. So the low priority placementID will have a longer latency of ad availability . 
IOS-2833
> [IOS-2833]Fix ad availability delays issue

- adapters/Vungle/VungleAdapter/GADMAdapterVungleBannerRequest.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleDelegate.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleInterstitial.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
For AdMob latest comments in Vungle 6.5.3.0 official PR (https://github.com/googleads/googleads-mobile-ios-mediation/pull/197#discussion_r398273717),  AdMob suggested us should change the `_bannerDelegates` back to use `NSMapTable<GADMAdapterVungleBannerRequest *, id<GADMAdapterVungleDelegate>>`. 
AdMob said we don't need to track the old banner delegate lifecycle after AdMob SDK removes it (AdMob mentioned "If Google SDK is dropping the instance, it means we also dropped the ad that the adapter is responding to. So the callback likely isn't doing anything anyway (or if it's making it back, it's only because the adapter didn't let things get cleaned up)"). 
I have checked the `- (void)willCloseAd:didDownload:` and  ` - (void)didCloseAd:didDownload:` delegate methods don‘t do anything …
> [IOS-2885]Implement AdMob suggestion

- adapters/Vungle/VungleAdapter/GADMAdapterVungleBannerRequest.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleBannerRequest.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleInterstitial.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
AdMob made a new comment after they tested our 6.5.3 Adapter (https://github.com/googleads/googleads-mobile-ios-mediation/pull/197#discussion_r403400924).
AdMob has asked us to assume if we get Banner AdRequest with no unique ID in case Pub did not implement our integration suggestion to register `VungleAdNetworkExtras`,  so uniqueID is nil. For the next Banner ad request with same placementID, adapter cannot determine if it for the refresh or for another new Banner ad request, the adapter will refuse to load next Banner ad request with same placementID.
Android side already implemented this suggestion. This suggestion will have some side effect on reducing chances for Vungle to fill for Banner refresh, if current request is already filled by Vungle and Banner is already been shown, but …
> [IOS-2910]Implement AdMob suggestion of refresh checking

- adapters/Vungle/CHANGELOG.md
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
Currently when Banner ad is requested with different ad size from the size of `cached ad`, `loadPlacementWithID` in `VunglePlacementsCoordinator` will return `Yes` and not return `NO` or `error` any more in our native SDK. So we could remove the `VungleSDKResetPlacementForDifferentAdSize` error code check when requesting a different Banner ad size from the size of `cached Banner ad`.
IOS-3245
> [IOS-3245]Remove ResetPlacementForDifferentAdSize error check

- adapters/Vungle/VungleAdapter/GADMAdapterVungleBanner.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleDelegate.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleInterstitial.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRewardedAd.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
This PR is implementing the new SDK callback `vungleAdViewedForPlacement:` in AdMob adapter. Base on the synchronization result of Aki, Clarke with AdMob side:
Interstitial：  Vungle: - (void)vungleAdViewedForPlacement: -> AdMob: adapterWillPresentInterstitial
Rewarded Ad：   Vungle: - (void)vungleAdViewedForPlacement: -> AdMob: reportImpression
IOS-3432
> [IOS-3432]Implement new SDK callback `vungleAdViewedForPlacement:` in AdMob adapter 

- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
This PR is enabling background downloading by default in 6.9.1.0 AdMob Adapter.
IOS-3809
> [IOS-3809]Enable background downloading by default

- adapters/Vungle/Public/Headers/VungleAdapter.h
- adapters/Vungle/VungleAdapter.xcodeproj/project.pbxproj
- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleBanner.h
- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleBanner.m
- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleInterstitial.h
- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleInterstitial.m
- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleRewardedAd.h
- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleRewardedAd.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleBanner.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleDelegate.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleInterstitial.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRewardBasedVideoAd.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRewardBasedVideoAd.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
- adapters/Vungle/VungleAdapter/GADMediationAdapterVungle.h
- adapters/Vungle/VungleAdapter/GADMediationAdapterVungle.m
Adding the Open Bidding implementation to the AdMob adapter. GADMediationAdapterVungle now implements GADRTBAdapter instead of GADMediationAdapter. The VungleRouter implements the new VungleSDKHBDelegate. The Banner and Interstitial classes now implement their respective Mediation classes. The old interstitial class needs to remain as a router to the real adapter class, similar to the old rewarded class. The ad format classes are moved under "OpenBidding", but they can be moved under "AdFormats" instead. Arbitrary name.
IOS-3806
Tested with iOS Simulator and iPhone 8 Plus with the mock HB responses from AdMob.
> [IOS-3806] Updating adapter to handle Open Bidding

- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
Fixing the playAd methods overriding the global mute with the value in the extras object.
IOS-4299
> Fixing the playAd methods overriding the global mute with the value in the extras object.

- adapters/Vungle/Public/Headers/VungleAdNetworkExtras.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
- adapters/Vungle/VungleAdapter/VungleAdNetworkExtras.m
Updating adapter to not write the muted flag in the play options if it was never set by the publisher.
IOS-4436
> [IOS-4436] Updating adapter to not write the muted flag in the play options if it was never set by the publisher.

- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleBanner.m
- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleInterstitial.m
- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleNativeAd.m
- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleRewardedAd.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleBanner.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleDelegate.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleInterstitial.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
Adding the didShow callback to the VungleDelegate and utilizing the callback to call the Google didStartVideo.
IOS-4517
Only the rewarded format utilizes the didShow callback; the other formats have no action. I tested this with the Simulator by placing a breakpoint on the didShow callback in the rewarded ads class to test that it is invoked.
> [IOS-4517] Adding the didShow callback to the VungleDelegate and utilizing the callback to call the Google didStartVideo.

- adapters/Vungle/Public/Headers/VungleAdNetworkExtras.h
- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleNativeAd.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleConstants.h
Updating adapter to consume the native ad options position in the network extras object.
IOS-4570
Tested in the iOS Simulator with the IOS-4570 branch and a local merge to the native-qa branch (which points the test app to the qa endpoint and changes the ad unit id to one that works since native ads aren't on production yet.
> [IOS-4570] Updating adapter to consume the native ad options position in the network extras object.

- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleNativeAd.m
Updating the native ad to use the sponsoredText as the advertiser.
IOS-4566
> [IOS-4566] Updating the native ad to use the sponsoredText as the advertiser.

- adapters/Vungle/VungleAdapter/GADMAdapterVungleInterstitial.m
- adapters/Vungle/VungleAdapter/GADMediationAdapterVungle.m
This commit fixes the COPPA status issue. The API has changed from returning a BOOL to NSNumber.
IOS-5357, IOS-5358
> [IOS-5357, IOS-5358] This commit fixes the COPPA status issue.

- adapters/Vungle/VungleAdapter/GADMAdapterVungleBanner.m
Updating the ad size filter to have a direct match for MREC, otherwise to assume it is a banner ad with a flexible size.
IOS-5483
> [IOS-5483] Updating the ad size filter to have a direct match for MREC

- adapters/Vungle/Public/Headers/VungleAdNetworkExtras.h
- adapters/Vungle/VungleAdapter.xcodeproj/project.pbxproj
- adapters/Vungle/VungleAdapter/GADMAdapterVungleInterstitial.m
- adapters/Vungle/VungleAdapter/GADMediationAdapterVungle.m
- adapters/Vungle/VungleAdapter/VungleRouterConsentPrivate.h
This commit re-adds the properties that were removed and a deprecated attribute is attached to the property.
IOS-5491
> [IOS-5491] This commit re-adds the properties that were removed and a deprecated attribute is attached to the property.

- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleInterstitial.m
- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleNativeAd.m
- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleRewardedAd.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleBanner.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleInterstitial.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRewardBasedVideoAd.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleUtils.h
- adapters/Vungle/VungleAdapter/GADMAdapterVungleUtils.m
This commit updates the error object sent to the Google SDK to use their error codes. The vungle error code is embedded into the description.
IOS-5489
> [IOS-5489] This commit updates the error object sent to the Google SDK to use their error codes.

- adapters/Vungle/VungleAdapter/Bidding/GADMediationVungleInterstitial.m
- adapters/Vungle/VungleAdapter/GADMAdapterVungleRouter.m
This commit adds a report impression callback for bidding interstitial that Google pointed out in the 6.x PR. 
This commit brings back a set to fire delegates in case the publisher attempts to lazy initialize multiple ad units at once.
IOS-5700
> [IOS-5700] This commit fixes possible issues noticed during the documentation update.

- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/Bidding/GADMediationVungleBanner.m
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/Bidding/GADMediationVungleInterstitial.m
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/Bidding/GADMediationVungleNativeAd.m
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/Bidding/GADMediationVungleRewardedAd.m
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/GADMAdapterVungleBanner.m
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/GADMAdapterVungleInterstitial.m
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/GADMAdapterVungleRewardBasedVideoAd.m
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/GADMAdapterVungleRouter.m
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/GADMAdapterVungleUtils.h
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/GADMAdapterVungleUtils.m
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/GADMediationAdapterVungle.h
This commit updates the adapter to use the error objects from the SDK directly in most places. The Google documentation can be updated to point to the new Liftoff error code documentation
IOS-6305
https://support.vungle.com/hc/en-us/articles/15661036969627-Error-Codes-Vungle-SDK-for-iOS
> [IOS-6305] This commit updates the adapter to use the error objects from the SDK

- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/GADMAdapterVungleConstants.h
- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/GADMAdapterVungleUtils.m
Updating the MREC matching to be any size that can fit an MREC instead of being an exact match.
IOS-6470
> [IOS-6470] Updating the MREC matching to be any size that can fit an MREC instead of being an exact match.

- adapters/LiftoffMonetize/LiftoffMonetizeAdapter/Bidding/GADMediationVungleNativeAd.m
- adapters/LiftoffMonetize/Public/Headers/VungleAdNetworkExtras.h
This commit updates the privacy icon position handling to take into consideration the differences between the GAAdChoicesPosition enum and the NativeAdOptionsPosition enum.
IOS-7024
> [IOS-7024] Update privacy icon position handling

- adapters/LiftoffMonetize/Public/Headers/VungleAdNetworkExtras.h
This commit fixes a typo in VungleAdNetworkExtras documentation, updating so GADAdChoicesPosition is referenced correctly.
IOS-7024
> [IOS-7024] Fix typo in network extras documentation
